### ISSUE TITLE
Can you upgrade it to vue 3

### ISSUE THREAD

**Issue by bhojkamal** [Nagarjuna-PradeepKumar/hospital-management-system#14]
Hello,
Can you please upgrade to Vue 3 ?

**Comment by Nagarjuna-PradeepKumar** [comment]
hi @bhojkamal , The codes are written with Vuetify. Vuetify currently does not support Vue3 and is planned for release in Q3 2021. I am waiting for the release. Probably within a couple of months, Vuetify do not release then I would skip Vuetify and shift to Vue 3

**Comment by Nagarjuna-PradeepKumar** [comment]
The codes are written with Vuetify. Vuetify currently does not support Vue3 and is planned for release in Q3 2021. I am waiting for the release. Probably within a couple of months, Vuetify do not release then I would skip Vuetify and shift to Vue 3
